#!/bin/bash

#PBS -P rg47
#PBS -l ncpus=10
#PBS -l mem=100gb
#PBS -l walltime=24:00:00
#PBS -l wd
#PBS -q express
#PBS -l storage=gdata/rg47

module load fastqc
source /g/data/rg47/mw9045/miniconda3/etc/profile.d/conda.sh 
conda activate /g/data/rg47/mw9045/miniconda3/envs/Beeviromics

cd /g/data/rg47/mw9045/UKBombus_rRNA_alignment

fastqc -t 6 -q -o /g/data/rg47/mw9045/UKBombusBowtieFastQC *unmapped*fq.gz