#!/bin/bash

#PBS -P rg47
#PBS -l ncpus=48
#PBS -l mem=100gb
#PBS -l walltime=24:00:00
#PBS -l wd
#PBS -q express
#PBS -l storage=gdata/rg47

source /g/data/rg47/mw9045/miniconda3/etc/profile.d/conda.sh 
conda activate /g/data/rg47/mw9045/miniconda3/envs/Beeviromics

cd /g/data/rg47/mw9045/UKBOMBUSSTAR_alignment

STAR --runThreadN $PBS_NCPUS \
     --runMode genomeGenerate \
     --genomeDir /g/data/rg47/mw9045/BombusSTARgenome/Star-output_Bombus \
     --genomeFastaFiles /g/data/rg47/mw9045/BombusSTARgenome/GCF_910591885.1_iyBomTerr1.2_genomic.fa \
     --sjdbGTFfile /g/data/rg47/mw9045/BombusSTARgenome/GCF_910591885.1_iyBomTerr1.2_genomic.gtf \
     --genomeSAindexNbases 13